<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>BBSB.Core.Tests</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>BBSB_STANDALONE</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>9.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="Core/BBSB.Core.csproj" />
    <ProjectReference Include="Runtime/BBSB.Runtime.csproj" />
    <Compile Include="../../Assets/BBSB/Tests/EditMode/*.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
