// Generated by Tools/StageAssets/build_catalog.py. All times share the authored audio beat grid.
using System;
using System.Collections.Generic;

namespace BBSB.Core
{
    public sealed class GenreMapDefinition
    {
        public string Id { get; }
        public string Genre { get; }
        public string Name { get; }
        internal GenreMapDefinition(string id, string genre, string name) { Id = id; Genre = genre; Name = name; }
    }

    public sealed class StageDefinition
    {
        public string Id => Music.Id;
        public string MapId { get; }
        public string Meter { get; }
        public string FieldDescription { get; }
        public MusicDefinition Music { get; }
        public string ResourceRoot => "BBSB/StageAssets/" + Id + "/";
        public string BackgroundPath => ResourceRoot + "background";
        public string AudioPath => ResourceRoot + "music";
        internal StageDefinition(string mapId, string meter, string field, MusicDefinition music)
        { MapId = mapId; Meter = meter; FieldDescription = field; Music = music; }
    }

    public static class StageCatalog
    {
        public static IReadOnlyList<GenreMapDefinition> Maps { get; } = Array.AsReadOnly(new[]
        {
            new GenreMapDefinition("POP", "팝", "프리즘 시티"),
            new GenreMapDefinition("RNB", "R&B", "벨벳 나이트"),
            new GenreMapDefinition("JAZZ", "재즈", "브라스 쿼터"),
            new GenreMapDefinition("RAP", "랩", "라임 블록"),
            new GenreMapDefinition("BARD", "바드코어", "양피지 왕국"),
            new GenreMapDefinition("CELT", "켈틱", "안개와 매듭의 섬"),
            new GenreMapDefinition("NEW", "뉴에이지", "여백의 정원"),
            new GenreMapDefinition("METAL", "메탈", "아이언 칼데라"),
        });
        public static IReadOnlyList<StageDefinition> All { get; } = Array.AsReadOnly(new[]
        {
            Define("POP-01", "POP", "첫 신호등", 120, 4, 40, "4/4", "둥근 모서리의 직사각 광장. 가장자리 횡단보도 줄무늬."),
            Define("POP-02", "POP", "소다 루프탑", 108, 4, 36, "4/4", "넓은 캡슐 모양의 옥상 바닥. 배수로는 외곽에 배치."),
            Define("POP-03", "POP", "캔디 아케이드", 132, 4, 44, "4/4", "팔각형 타일 코트. 모서리에만 작은 컬러 조명."),
            Define("POP-04", "POP", "선셋 다이브", 96, 4, 32, "4/4", "물 옆의 부채꼴 데크. 전투 구역은 마른 바닥."),
            Define("POP-05", "POP", "문라이트 롤러", 120, 4, 40, "4/4", "둥근 직사각 나무 코트. 외곽 트랙은 장식."),
            Define("POP-06", "POP", "구름 쇼핑몰", 108, 4, 36, "4/4", "육각형 유리 테라스. 중앙에는 불투명 무광 바닥."),
            Define("POP-07", "POP", "색종이 퍼레이드", 132, 4, 44, "4/4", "폭이 넓은 사다리꼴 도로 무대. 중앙은 단색."),
            Define("POP-08", "POP", "심야 라디오", 96, 4, 32, "4/4", "비스듬한 모서리의 직사각 철제 전망대."),
            Define("POP-09", "POP", "네온 익스프레스", 144, 4, 48, "4/4", "폭이 넓은 열차 객실 바닥. 창밖 이동은 느리게."),
            Define("POP-10", "POP", "프리즘 스카이라인", 120, 4, 40, "4/4", "크고 평평한 다이아몬드형 전망대. 옆면만 발광."),
            Define("RNB-01", "RNB", "빗방울 윈도", 72, 4, 24, "4/4", "넓은 반원형 창가 마루. 테이블은 양쪽 끝에만."),
            Define("RNB-02", "RNB", "바이닐 라운지", 84, 4, 28, "4/4", "회전판을 닮은 원형 짙은 나무 바닥. 중앙 회전 없음."),
            Define("RNB-03", "RNB", "세탁소 새벽 두 시", 96, 4, 32, "4/4", "둥근 직사각 리놀륨 바닥. 세탁기는 후방 벽에."),
            Define("RNB-04", "RNB", "커튼 너머 달빛", 72, 4, 24, "4/4", "넓은 부채꼴 석재 발코니. 난간은 뒤로 낮게."),
            Define("RNB-05", "RNB", "막차 뒤 택시", 84, 4, 28, "4/4", "길쭉한 사다리꼴 승차장. 젖은 가장자리만 반사."),
            Define("RNB-06", "RNB", "미러 스카이워크", 96, 4, 32, "4/4", "모서리를 깎은 긴 직사각 통로. 중앙 유리는 불투명."),
            Define("RNB-07", "RNB", "온수풀의 잔향", 72, 4, 24, "4/4", "물가의 넓은 타원 석재 데크. 수증기는 뒤쪽."),
            Define("RNB-08", "RNB", "장미빛 안뜰", 84, 4, 28, "4/4", "둥근 모서리 사각 벽돌 광장. 식물은 외곽."),
            Define("RNB-09", "RNB", "새벽 항구선", 96, 4, 32, "4/4", "넓은 육각 목재 잔교. 난간 사이로 항구가 보임."),
            Define("RNB-10", "RNB", "벨벳 펜트하우스", 84, 4, 28, "4/4", "둥근 끝을 가진 직사각 무광 마루. 중앙 비움."),
            Define("JAZZ-01", "JAZZ", "골목 첫 세션", 108, 4, 36, "4/4", "평평한 반원형 벽돌 마당. 소품은 후방에."),
            Define("JAZZ-02", "JAZZ", "커피잔 왈츠", 108, 3, 48, "3/4", "넓은 원형 목재 바닥. 세 박의 장식은 외곽에."),
            Define("JAZZ-03", "JAZZ", "블루 플랫폼", 96, 4, 32, "4/4", "넓은 직사각 플랫폼. 선로는 뒤쪽 아래로."),
            Define("JAZZ-04", "JAZZ", "황동 우편실", 120, 4, 40, "4/4", "모서리를 깎은 사각 대리석 홀."),
            Define("JAZZ-05", "JAZZ", "유리 온실 보사", 96, 4, 32, "4/4", "타원형 테라코타 타일 바닥. 식물 그림자는 약하게."),
            Define("JAZZ-06", "JAZZ", "자정 포켓클럽", 132, 4, 44, "4/4", "너비가 충분한 부채꼴 나무 무대."),
            Define("JAZZ-07", "JAZZ", "브리지 블루스", 108, 4, 36, "4/4", "넓은 사다리꼴 콘크리트 쉼터."),
            Define("JAZZ-08", "JAZZ", "시계탑 트리오", 144, 3, 64, "3/4", "팔각형 나무 바닥. 톱니는 전투면 밖에."),
            Define("JAZZ-09", "JAZZ", "황금빛 급행", 156, 4, 52, "4/4", "중앙을 비운 긴 직사각 카펫 바닥."),
            Define("JAZZ-10", "JAZZ", "브라스 돔 앙코르", 120, 4, 40, "4/4", "커다란 반원형 무광 목재 무대."),
            Define("RAP-01", "RAP", "분필 코트", 96, 4, 32, "4/4", "둥근 모서리 직사각 코트. 분필은 테두리에만."),
            Define("RAP-02", "RAP", "지하철 싸이퍼", 84, 4, 28, "4/4", "팔각형 회색 타일 공간. 기둥은 후방 양끝."),
            Define("RAP-03", "RAP", "옥상 안테나", 96, 4, 32, "4/4", "사다리꼴 콘크리트 옥상. 중앙은 깨끗하게."),
            Define("RAP-04", "RAP", "레코드 골목", 108, 4, 36, "4/4", "넓은 캡슐형 보행 광장."),
            Define("RAP-05", "RAP", "컨테이너 베이스", 144, 4, 48, "4/4", "커다란 직사각 철판 바닥. 중앙 반사는 억제."),
            Define("RAP-06", "RAP", "터널 드립", 132, 4, 44, "4/4", "모서리를 깎은 사각 마른 정비대."),
            Define("RAP-07", "RAP", "야시장 마이크", 108, 4, 36, "4/4", "넓은 육각 포장석 광장. 가판은 가장자리."),
            Define("RAP-08", "RAP", "스케이트 플로", 120, 4, 40, "4/4", "넓고 평평한 타원 콘크리트 패드. 경사는 외곽."),
            Define("RAP-09", "RAP", "폐극장 벌스", 84, 4, 28, "4/4", "넓은 부채꼴 무대. 파손은 전투면 밖에."),
            Define("RAP-10", "RAP", "블록 파티 피날레", 96, 4, 32, "4/4", "커다란 둥근 사각 아스팔트 광장."),
            Define("BARD-01", "BARD", "아침 종과 장터", 120, 4, 40, "4/4", "넓은 둥근 사각 자갈 광장. 중앙 패턴은 단순."),
            Define("BARD-02", "BARD", "참나무 여관", 96, 4, 32, "4/4", "반원형 넓은 참나무 마루. 식탁은 양끝."),
            Define("BARD-03", "BARD", "풍차 언덕길", 108, 3, 48, "3/4", "넓은 타원형 다진 흙 공터. 경사는 뒤쪽 풍경."),
            Define("BARD-04", "BARD", "왕실 우편마차", 120, 4, 40, "4/4", "육각형 포장석 마차 회차장."),
            Define("BARD-05", "BARD", "붉은 벽돌 공방", 132, 4, 44, "4/4", "넓은 직사각 벽돌 작업장. 불은 후방에."),
            Define("BARD-06", "BARD", "양피지 도서탑", 72, 2, 48, "6/8", "넓은 팔각 석재 홀. 책상은 외곽."),
            Define("BARD-07", "BARD", "가면무도 회랑", 108, 3, 48, "3/4", "모서리를 둥글린 직사각 흑백 돌바닥. 중앙은 무늬 완화."),
            Define("BARD-08", "BARD", "해자 위 나무다리", 120, 4, 40, "4/4", "폭넓은 사다리꼴 나무다리. 전투 중 각도 고정."),
            Define("BARD-09", "BARD", "깃발의 토너먼트", 144, 4, 48, "4/4", "크고 평평한 타원 모래 코트. 깃발은 높은 배경에."),
            Define("BARD-10", "BARD", "왕관 없는 연회", 120, 4, 40, "4/4", "넓은 부채꼴 목재 연회 바닥. 중앙에는 가구 없음."),
            Define("CELT-01", "CELT", "헤더빛 나루", 72, 2, 48, "6/8", "넓은 반원형 돌 선착장. 물은 뒤쪽."),
            Define("CELT-02", "CELT", "참나무 원무", 120, 4, 40, "4/4", "완만한 원형 잔디 바닥. 뿌리는 경계 밖으로."),
            Define("CELT-03", "CELT", "달빛 징검여울", 72, 2, 48, "6/8", "하나로 이어진 넓은 타원 돌판. 발 디딜 곳은 끊기지 않음."),
            Define("CELT-04", "CELT", "바람의 양목장", 84, 2, 56, "6/8", "넓은 캡슐형 흙길 쉼터. 풀은 외곽."),
            Define("CELT-05", "CELT", "돌고리의 약속", 96, 4, 32, "4/4", "넓은 원형 회색 돌바닥. 문양은 테두리 띠에."),
            Define("CELT-06", "CELT", "은빛 폭포길", 84, 2, 56, "6/8", "넓은 부채꼴 돌 전망대. 물보라는 뒤로."),
            Define("CELT-07", "CELT", "이끼의 옛 다리", 120, 4, 40, "4/4", "평평하고 넓은 사다리꼴 다리 중앙부."),
            Define("CELT-08", "CELT", "등대의 파도춤", 96, 2, 64, "6/8", "팔각형 석재 등대 앞마당. 파도는 난간 밖."),
            Define("CELT-09", "CELT", "별매듭 언덕", 108, 3, 48, "3/4", "둥근 모서리의 다이아몬드형 풀밭 공터."),
            Define("CELT-10", "CELT", "안개 왕관 절벽", 120, 4, 40, "4/4", "넓은 반원형 암반. 전투면은 평탄하게."),
            Define("NEW-01", "NEW", "물거울 새벽", 72, 4, 24, "4/4", "넓은 타원형 연한 돌섬. 중앙 반사광은 억제."),
            Define("NEW-02", "NEW", "유리잎 온실", 84, 4, 28, "4/4", "넓은 육각형 무광 석재 바닥."),
            Define("NEW-03", "NEW", "모래시계 해변", 72, 2, 48, "6/8", "넓은 반원형 단단한 모래 공터."),
            Define("NEW-04", "NEW", "구름 우편함", 96, 4, 32, "4/4", "둥근 사각의 넓은 잔디 섬. 비행 움직임은 없음."),
            Define("NEW-05", "NEW", "자수정 동굴", 72, 4, 24, "4/4", "팔각형의 평평한 밝은 암반. 수정은 외곽."),
            Define("NEW-06", "NEW", "수련의 회랑", 84, 4, 28, "4/4", "넓은 부채꼴 목재 데크. 꽃잎은 후방 수면에."),
            Define("NEW-07", "NEW", "눈꽃 천문대", 108, 3, 48, "3/4", "커다란 원형 흰 돌바닥. 눈 입자는 배경에."),
            Define("NEW-08", "NEW", "부유섬의 오후", 96, 4, 32, "4/4", "넓은 사다리꼴 석재 테라스. 중앙은 평탄."),
            Define("NEW-09", "NEW", "오로라 호수", 72, 2, 48, "6/8", "넓은 타원형 얼음 위 무광 눈 덮인 바닥."),
            Define("NEW-10", "NEW", "여백의 중심", 84, 4, 28, "4/4", "넓은 둥근 사각 백색 석재 마당."),
            Define("METAL-01", "METAL", "재의 입구", 120, 4, 40, "4/4", "넓은 사다리꼴 현무암 입구. 중앙은 단순."),
            Define("METAL-02", "METAL", "쇠사슬 교각", 144, 4, 48, "4/4", "넓은 직사각 철판 교량. 전투 중 흔들리지 않음."),
            Define("METAL-03", "METAL", "검은 증기기관", 132, 4, 44, "4/4", "모서리를 깎은 사각 철제 정비 바닥."),
            Define("METAL-04", "METAL", "붉은 주조장", 156, 4, 52, "4/4", "넓은 육각 철제 플랫폼. 금속 흐름은 후방 아래."),
            Define("METAL-05", "METAL", "폐성의 파워코드", 144, 4, 48, "4/4", "넓은 반원형 돌 성벽 마당. 잔해는 바깥."),
            Define("METAL-06", "METAL", "심연 채굴장", 96, 4, 32, "4/4", "넓은 타원형 암반 작업장. 절벽은 뒤쪽."),
            Define("METAL-07", "METAL", "번개 송전탑", 168, 4, 56, "4/4", "팔각형 검은 철제 전망대. 번개는 먼 하늘 한쪽."),
            Define("METAL-08", "METAL", "흑요석 대성당", 108, 2, 72, "6/8", "넓은 부채꼴 무광 흑요석 바닥."),
            Define("METAL-09", "METAL", "철심 회전로", 180, 4, 60, "4/4", "넓은 원형 철판 작업대. 발판 자체는 고정."),
            Define("METAL-10", "METAL", "칼데라 앙코르", 144, 4, 48, "4/4", "넓은 다이아몬드형 현무암 무대. 용암은 아래 멀리."),
        });
        public static GenreMapDefinition Map(string id)
        { foreach (var map in Maps) if (map.Id == id) return map; throw new ArgumentException("Unknown map: " + id, nameof(id)); }
        public static StageDefinition Find(string id)
        { foreach (var stage in All) if (stage.Id == id) return stage; return null; }

        public static GenreMapDefinition ThemeFor(int seed, int field, string startingMapId = null)
        {
            if (field < 1) throw new ArgumentOutOfRangeException(nameof(field));
            var maps = new List<GenreMapDefinition>(Maps);
            new SeededRandom(BattlePlanner.Hash(seed, "genre-map-order")).Shuffle(maps);
            if (startingMapId != null)
            {
                var first = Map(startingMapId); maps.Remove(first); maps.Insert(0, first);
            }
            return maps[(field - 1) % maps.Count];
        }
        public static StageDefinition ForEncounter(int seed, int field, int row, int column, string startingMapId = null)
        {
            if (row < 0 || row >= FieldMap.StageCount || column < 0 || column >= FieldMap.Width)
                throw new ArgumentOutOfRangeException(nameof(row));
            string mapId = ThemeFor(seed, field, startingMapId).Id;
            var songs = new List<StageDefinition>();
            foreach (var stage in All) if (stage.MapId == mapId) songs.Add(stage);
            new SeededRandom(BattlePlanner.Hash(seed, "songs/" + field + "/" + mapId)).Shuffle(songs);
            return songs[(row * FieldMap.Width + column) % songs.Count];
        }
        public static void Assign(FieldMap map, int seed, string startingMapId = null)
        {
            if (map == null) throw new ArgumentNullException(nameof(map));
            map.Theme = ThemeFor(seed, map.Number, startingMapId);
            foreach (var node in map.Nodes)
                node.SongId = node.IsBattle ? ForEncounter(seed, map.Number, node.Row, node.Column, startingMapId).Id : null;
        }
        public static int[] HookBars(int bars) => new[]
        { Math.Max(4, (int)(bars * .22) / 4 * 4), (int)(bars * .52) / 4 * 4, bars - (bars == 24 ? 6 : 8) };

        private static StageDefinition Define(string id, string mapId, string name, int bpm, int beats, int bars, string meter, string field)
        {
            var hooks = HookBars(bars);
            var points = new SortedSet<int> { 0, 2, bars - 2, bars };
            foreach (int hook in hooks) { points.Add(hook); points.Add(hook + 4); }
            var boundaries = new List<int>(points); var sections = new List<MusicSection>();
            for (int i = 0; i < boundaries.Count - 1; i++)
            {
                int start = boundaries[i], hook = Array.IndexOf(hooks, start);
                bool response = start != 0 && start != bars - 2;
                sections.Add(new MusicSection(hook >= 0 ? "HOOK " + (hook + 1) : start == 0 ? "INTRO" : start == bars - 2 ? "OUTRO" : "GROOVE",
                    start, boundaries[i + 1] - start, hook >= 0 ? 2.4 : 1, response, hook >= 0));
            }
            // Main beats and half beats accommodate the authored species, without moving their Calls.
            // Compound 6/8 uses two dotted-quarter pulses per bar, at the displayed BPM.
            var slots = new List<SlotTemplate>();
            for (int tick = 0; tick < beats * RhythmTime.TicksPerBeat; tick += 2)
            {
                double weight = tick % 4 == 0 ? 1.3 : .8;
                foreach (var kind in new[] { GestureKind.Tap, GestureKind.Flick, GestureKind.Shake })
                    slots.Add(new SlotTemplate(kind, tick, weight: weight));
                foreach (int length in new[] { 4, 8, 16 })
                    foreach (var kind in new[] { GestureKind.Hold, GestureKind.Dive })
                        slots.Add(new SlotTemplate(kind, tick, length, weight));
            }
            return new StageDefinition(mapId, meter, field, new MusicDefinition(id, name, bpm, beats, sections, new[] { slots }));
        }
    }
}
